"""
370 daily affirmations for the shop page.
Faith-rooted, inclusive, peaceful, and uplifting. No em-dashes. 1-2 lines each.
"""

AFFIRMATIONS = [
    # Being seen and known
    "You were made on purpose, for a purpose.",
    "There is grace enough for today.",
    "You are worthy of every good thing coming your way.",
    "Peace is possible, even on the hard days.",
    "You are deeply loved, even when you forget it.",
    "Your presence in this world matters more than you know.",
    "Something beautiful is growing in you right now.",
    "You do not have to earn rest. You deserve it.",
    "Let today be gentle with you.",
    "You are not behind. You are right where you need to be.",
    "The world is better because you are in it.",
    "You carry more strength than you have ever had to use.",
    "Today is a fresh start, no matter what yesterday looked like.",
    "Your story is still being written.",
    "You are seen, you are known, you are loved.",
    "Healing is not linear, and that is okay.",
    "You have already survived everything that tried to stop you.",
    "Joy gets to belong to you.",
    "You are allowed to take up space.",
    "Nothing about you is an accident.",

    # Peace and rest
    "Slow and steady is still movement.",
    "You are braver than you give yourself credit for.",
    "Good things are on their way to you.",
    "You are someone's answered prayer.",
    "Rest is not giving up. Rest is trusting.",
    "You are held, even when it does not feel that way.",
    "Your kindness ripples further than you can see.",
    "Today, be soft with yourself.",
    "You are not your hardest season.",
    "What is meant for you will find you.",
    "You are loved in your fullness, not just your best moments.",
    "There is more ahead of you than behind you.",
    "You bring something to this world no one else can.",
    "Gratitude opens doors that worry cannot.",
    "You are exactly enough, right now.",
    "The light in you is real, even on cloudy days.",
    "Your best is always enough.",
    "You get to choose how today begins.",
    "Something good is always possible.",
    "You are not carrying this alone.",

    # Calm and stillness
    "Peace does not require perfection.",
    "You deserve the same grace you give to everyone else.",
    "There is enough time for what truly matters.",
    "Your worth is not measured by your productivity.",
    "Let go of what was never yours to carry.",
    "You are allowed to rest before you are exhausted.",
    "Calm is available to you in any moment.",
    "You are safe. You are loved. You are enough.",
    "Stillness is not stagnation. It is preparation.",
    "You are allowed to change your mind.",
    "What you nurture in quiet moments shapes who you become.",
    "Your pace is your own. Honor it.",
    "Peace begins with the belief that you are worth it.",
    "You can start over at any moment. That is not failure. That is wisdom.",
    "Today, let gentleness lead.",
    "You have permission to exhale.",
    "Everything you need is already within reach.",
    "You do not need to rush your healing.",
    "The best thing you can do today is be kind to yourself.",
    "Breathe. This moment is yours.",

    # Courage and strength
    "Courage is just trust in motion.",
    "You have faced hard things before and found your way through.",
    "You are stronger than the version of you that felt afraid.",
    "The step in front of you is the only one that matters right now.",
    "You were built for this.",
    "Fear is not evidence of weakness. It is proof you care.",
    "You do not need to see the whole staircase. Just the next step.",
    "You have permission to try.",
    "Do not shrink to make others comfortable with your growth.",
    "Your dreams deserve a seat at the table.",
    "Boldness looks good on you.",
    "You have already overcome things that seemed impossible.",
    "Trust yourself a little more today.",
    "Your effort matters, even when results are not visible yet.",
    "Every time you show up, it counts.",
    "You are building something the world cannot yet see.",
    "The hardest days are often the ones that grow you most.",
    "You are not limited by what has been. You are defined by what you choose.",
    "Do not apologize for taking up the room your spirit fills.",
    "Keep going. Something wonderful is waiting.",

    # Love and worth
    "You are loved on your worst day, not just your best.",
    "Love does not have to be earned. It is already yours.",
    "You are worthy of kindness, most of all from yourself.",
    "Let someone love you well today.",
    "You are someone's reason to smile.",
    "The love you give always finds its way back to you.",
    "You matter to more people than you realize.",
    "You are irreplaceable.",
    "Your love is one of the most powerful forces in someone's life.",
    "Be gentle with yourself. You are a soul in process.",
    "You are worth fighting for.",
    "Your heart is a gift to everyone it touches.",
    "You deserve a love that feels like home.",
    "You are cherished for exactly who you are.",
    "There is always more room for the real you.",
    "You are lovable, even on the days you forget it.",
    "Your softness is not weakness. It is one of your greatest strengths.",
    "You are held in a love that never gives up on you.",
    "Even on the days you cannot see it, you are treasured.",
    "The world is softer because of your presence in it.",

    # Purpose and calling
    "You were not made to blend in.",
    "Purpose finds those who keep showing up.",
    "What you do with ordinary days creates an extraordinary life.",
    "Your calling is specific, personal, and real.",
    "You have gifts the world is waiting to receive.",
    "Living on purpose starts with one intentional choice.",
    "You are exactly where you need to be to become who you are meant to be.",
    "Your life is a story worth telling.",
    "Your work has meaning, even when it feels small.",
    "You were placed here, in this time, on purpose.",
    "The things that set you apart are not flaws. They are features.",
    "You are not here by mistake.",
    "Something you do today will outlast you.",
    "Your vision matters. Do not let fear talk you out of it.",
    "Purpose does not always announce itself loudly. Sometimes it whispers.",
    "You are the answer to someone's prayer you do not even know about.",
    "Do not minimize what you are here to do.",
    "Your uniqueness is the whole point.",
    "Every day you live your values, you leave a mark that matters.",
    "You are part of something larger than yourself.",

    # Growth and healing
    "You are not the worst version of yourself.",
    "Growth does not happen in straight lines, and that is perfectly okay.",
    "You are not broken. You are in process.",
    "Every step toward healing is a victory, no matter how small.",
    "You are allowed to grow at your own pace.",
    "What you have survived makes you someone remarkable.",
    "Grace is not something you earn. It is something you receive.",
    "The version of you ten years from now will be grateful you kept going.",
    "You can be a work in progress and still be worthy of love.",
    "Your pain has not been wasted.",
    "Healing happens slowly, then all at once.",
    "You are more whole than you feel on your hardest days.",
    "Choosing yourself is not selfish. It is necessary.",
    "You are not defined by your lowest moment.",
    "Redemption is always possible. Your story is not over.",
    "Each day you choose growth, something shifts.",
    "You do not have to have it all figured out to move forward.",
    "Let today be the day you stop being hard on yourself.",
    "You are becoming. And that is beautiful.",
    "Give yourself permission to be a beginner.",

    # Faith and trust
    "Faith is trusting before you can fully see.",
    "You are held by a love that does not waver.",
    "Let your heart be at rest. You are not alone in this.",
    "The uncertainty you feel today is not the end of your story.",
    "Trust the timing of your life.",
    "What feels like waiting is often preparation.",
    "You do not have to understand it all to trust through it.",
    "Something bigger is working on your behalf.",
    "Surrender is not weakness. It is the highest form of strength.",
    "You are carried, even when you cannot feel it.",
    "What was meant to harm you will be used for good.",
    "Faith is not the absence of doubt. It is choosing hope anyway.",
    "You are never too far from grace.",
    "The peace that passes understanding is available to you right now.",
    "Trust your path, even the parts that confuse you.",
    "You are being shaped by things you cannot always see.",
    "Hope is an act of courage.",
    "You are always closer to a breakthrough than you think.",
    "Let go and trust the hands that hold you.",
    "You do not have to carry tomorrow's weight today.",

    # Joy and gratitude
    "Gratitude turns ordinary moments into gifts.",
    "Joy is available to you right now, even in the small things.",
    "There is beauty around you that is easy to miss.",
    "A grateful heart attracts more to be grateful for.",
    "Today has blessings woven into it. Look for them.",
    "The small joys are the real ones.",
    "You can choose joy and still acknowledge hard things. Both are true.",
    "There is something good happening, even now.",
    "Laughter is a kind of medicine.",
    "Let yourself be happy. You have permission.",
    "Counting your blessings is not naive. It is powerful.",
    "Your ordinary life holds extraordinary moments.",
    "Joy does not depend on circumstances. It is a posture of the heart.",
    "Celebrate the small wins. They are not small.",
    "You are surrounded by more beauty than you notice on rushed days.",
    "Be present enough to feel the good that is already here.",
    "This moment, right now, is a gift.",
    "Let delight be part of your day.",
    "Thankfulness is a form of faith.",
    "The best parts of your life are the ones you choose to notice.",

    # Identity and belonging
    "You belong exactly where you are.",
    "You do not have to shrink to fit in.",
    "There are people who are glad you exist.",
    "You are not too much. You are exactly enough.",
    "You belong in rooms that feel too big for you.",
    "The community you are looking for is also looking for you.",
    "You have a seat at the table. You were invited.",
    "Your presence changes every room you walk into.",
    "You are not forgotten. You are not overlooked.",
    "Home is sometimes a feeling, and you can build it anywhere.",
    "You were made to be known, not just seen.",
    "Connection is worth the risk of being seen.",
    "You are not too late to find your people.",
    "You are wanted, even when loneliness lies and says otherwise.",
    "Your story connects you to more people than you realize.",
    "Let someone in today. You were not meant to do this alone.",
    "You are part of something. Even when it does not feel that way.",
    "The places that shaped you prepared you for where you are going.",
    "Being known fully and loved fully at the same time is possible.",
    "You belong to this world in a way no one else does.",

    # New beginnings
    "Something new is beginning for you.",
    "The season you are in is not the only season ahead.",
    "What you are planting now will bloom in ways you cannot yet imagine.",
    "You are not stuck. You are in a season of preparation.",
    "Change can be scary and still be exactly what you need.",
    "New chapters require stepping away from old ones. That is brave.",
    "You are right on the edge of something good.",
    "The best is not behind you.",
    "God is not done writing your story.",
    "Let this season teach you what only it can.",
    "You are growing in directions you cannot yet measure.",
    "The roots you build in quiet seasons support everything that comes after.",
    "What feels like an ending is often a beginning in disguise.",
    "You are not stuck. You are being refined.",
    "New possibilities are never far from where you stand.",
    "You are allowed to want more for your life.",
    "Dreams are not too big when they are tied to your purpose.",
    "Something worth waiting for is coming.",
    "This chapter is not the whole book.",
    "You are exactly where the next great thing begins.",

    # Progress and resilience
    "You are a good person doing your best.",
    "Give yourself credit for how far you have already come.",
    "You have survived one hundred percent of your hardest days.",
    "The version of you today is stronger than the one from before.",
    "Your consistency is creating something beautiful.",
    "You show up even when it is hard. That matters.",
    "Do not compare your chapter two to someone else's chapter ten.",
    "You are making progress, even when you cannot see it.",
    "Your quiet faithfulness is not invisible.",
    "Every day you keep going, something is being built.",
    "You are not behind. You are on your own timeline.",
    "Do not minimize what you have already overcome.",
    "You are already doing better than you think.",
    "The small acts of love you give are building a life worth having.",
    "Look back and see how far you have come.",
    "You are more resilient than you give yourself credit for.",
    "Progress is still progress, even when it is slow.",
    "Your daily choices are creating the life you want.",
    "You have come so far. Keep going.",
    "You are the proof that hard things do not last forever.",

    # Self-compassion
    "Be kind to the version of you that is still learning.",
    "You are worthy of the patience you give to others.",
    "Treat yourself like someone you love.",
    "You are a whole person, not a to-do list.",
    "Rest is not laziness. It is maintenance for your best self.",
    "You do not have to earn your value. You were born with it.",
    "You are not a burden. You are a blessing.",
    "Your needs matter. Do not minimize them.",
    "Saying no to the wrong things is saying yes to the right ones.",
    "You are allowed to set limits that protect your peace.",
    "Taking care of yourself is taking care of everyone you love.",
    "Your health, your joy, and your peace are worth protecting.",
    "You are allowed to put yourself on your own list.",
    "Honoring your limits is a form of wisdom.",
    "You cannot pour from an empty vessel. Let yourself be refilled.",
    "You are worth the same investment you give to others.",
    "Do something today that is just for you.",
    "Your energy is precious. Guard it well.",
    "Self-compassion is not indulgence. It is survival.",
    "You are worthy of your own kindness.",

    # Forgiveness and second chances
    "You are not your failures. You are what you choose next.",
    "A mistake is not the end of your story. It is a chapter.",
    "You are allowed to forgive yourself and move on.",
    "What you did wrong does not define what you will do next.",
    "Grace is not just for other people. It is for you too.",
    "You are not condemned by your past.",
    "Tomorrow is full of possibilities that today's mistakes cannot erase.",
    "You are more than your worst moment.",
    "There is no failure in trying. There is only learning.",
    "You are free to begin again.",

    # Wonder and beauty
    "Beauty is in the everyday details you almost walked past.",
    "You are living a life that someone else is praying for.",
    "What you have right now is someone else's dream. Let that land.",
    "Look for the wonder. It is almost always there.",
    "Your life, exactly as it is, holds more magic than you notice.",
    "There is something holy about ordinary Tuesdays.",
    "Pay attention to the small graces. They are everywhere.",
    "The most meaningful parts of your life are not found in the big moments.",
    "Today holds something worth noticing.",
    "Slow down long enough to let the good things touch you.",

    # Kindness and impact
    "You are kind, and that is one of the most powerful things a person can be.",
    "Your presence is a gift, even when you do not feel like one.",
    "You inspire people you do not even know you inspire.",
    "The way you love people matters more than you realize.",
    "You are someone's safe place.",
    "People feel better after being around you. That is rare and beautiful.",
    "Your compassion is changing things.",
    "You make the world softer just by being in it.",
    "The love you extend, even in small ways, is never lost.",
    "Someone today will be changed by your kindness.",

    # Endurance
    "You are strong enough for this, even if you are not sure yet.",
    "Strength is not always loud. Sometimes it is quiet persistence.",
    "You are tougher than the thing that is trying to wear you down.",
    "Do not let the length of a season fool you into thinking it is permanent.",
    "You will look back on this and see what it was building in you.",
    "You are not fragile. You are flexible, and that is better.",
    "Even in weakness, you are held.",
    "The pressure you are under is shaping something remarkable.",
    "You will get through this because you have gotten through everything else.",
    "You are more than capable.",

    # Hope
    "Your story has always been heading somewhere good.",
    "The best chapters of your life may not have started yet.",
    "Hope is not wishful thinking. It is a choice.",
    "You are allowed to expect good things.",
    "There is always more ahead than there is behind.",
    "You get to rewrite any narrative that no longer serves you.",
    "You are not too old, too late, or too far gone for a new beginning.",
    "Better days are not just possible. They are coming.",
    "Do not let anyone convince you that your best is behind you.",
    "Your future is brighter than your past, by far.",

    # Spiritual grounding
    "Your faith, even the size of a small seed, is enough.",
    "You do not need to have it all together to receive grace.",
    "Every ordinary day is a gift from a God who does not forget you.",
    "You are known by name. You are not lost in the crowd.",
    "The love that made you is the same love that sustains you.",
    "You do not have to be perfect to be accepted.",
    "You are met with grace, not judgment, when you come as you are.",
    "The hands that hold the universe are also holding you.",
    "Your prayers are heard. Every single one.",
    "You are never too far, too broken, or too tired for grace to find you.",

    # Agency and choice
    "You get to decide what kind of day this is.",
    "Your attitude is one thing no one can take from you.",
    "Choose the thought that serves you best right now.",
    "You have more agency than it feels like today.",
    "One good decision right now can change the rest of the day.",
    "You get to write the next sentence.",
    "How you respond today is always your choice.",
    "You are the author of the part of this story that begins right now.",
    "Choose love when you can. It changes everything.",
    "Your choices today are shaping tomorrow. Choose well.",

    # Authenticity
    "You are not defined by the opinions of people who do not know your whole story.",
    "The voice that matters most is the one inside you that knows the truth.",
    "Do not let comparison steal the joy of where you are.",
    "You are running your own race. Eyes forward.",
    "The only version of you that matters is the most authentic one.",
    "You do not need approval to know your worth.",
    "Someone else's success does not diminish yours.",
    "You are not in competition with anyone but yesterday's version of yourself.",
    "Live your life for an audience of one.",
    "You are enough, as you are, today.",

    # Presence and stillness
    "Take a breath. You are doing better than you think.",
    "Be patient with yourself. Rome was not built in a day, and neither is a life.",
    "You cannot rush becoming. It takes time.",
    "Right now, this moment, is enough.",
    "You are allowed to just be today, without producing anything.",
    "The hustle is not the whole story. Rest is part of the plan.",
    "Peace is not something you find. It is something you choose.",
    "You can slow down without falling behind.",
    "Take your time. The things meant for you will wait.",
    "Today, just breathe. That is enough.",

    # Closing affirmations
    "You were thought of before you were born.",
    "There is a reason you are here. You may not see it all yet.",
    "You are not an afterthought. You are entirely intentional.",
    "Your life has divine fingerprints all over it.",
    "You are part of a story that is bigger than you can see right now.",
    "The one who made you knows every part of you and loves you still.",
    "You are not overlooked. You are chosen.",
    "Every part of your story, even the hard parts, has purpose.",
    "You were crafted with intention and crowned with worth.",
    "You are loved completely, known fully, and never alone.",
    "Your gentleness is a form of power.",
    "Showing up for yourself every day is one of the bravest things.",
    "You are a gift wrapped in ordinary days.",
    "The most meaningful thing you can do is be fully yourself.",
    "You are living proof that love wins.",
    "Let today be the beginning of something beautiful.",
    "Everything you need has already been placed within you.",
    "You are the light someone is waiting to see today.",
    "Be patient with your journey. The best things take time.",
    "You are held, you are loved, you are enough.",
]


def seed_affirmations(app):
    """Seed the affirmations table if it is empty. Safe to call multiple times."""
    with app.app_context():
        try:
            from models import db, Affirmation
            if Affirmation.query.count() == 0:
                import sys
                print("Seeding affirmations table...", file=sys.stderr, flush=True)
                for i, text in enumerate(AFFIRMATIONS):
                    db.session.add(Affirmation(text=text, is_active=True, sort_order=i))
                db.session.commit()
                print(f"Seeded {len(AFFIRMATIONS)} affirmations.", file=sys.stderr, flush=True)
        except Exception as e:
            import sys, traceback
            print(f"Affirmation seed failed: {e}", file=sys.stderr)
            traceback.print_exc(file=sys.stderr)
